services:
  viside-mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: viside-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./config/:/docker-entrypoint-initdb.d/
    ports:
      - 3307:3306
  viside-redis:
    image: redis
    container_name: viside-redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379